#server:
#  port: 9999
## adding a application name will help us to identify the application in Eureka server registry
#spring:
#  application:
#    name: spring-cloud-gateway
## enable gateway metrics in actuator
#  cloud:
#    gateway:
#      metrics:
#        enable: true
#      discovery:
#        locator:
#          lower-case-service-id: true
#          enable: true
## enable all end points in actuator
## visit http://localhost:9999/actuator by commenting and un commenting the below config to see the difference
#management:
#  endpoints:
#    web:
#      exposure:
#        include:  "*"
#    gateway:
#      enable: true
#
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          predicates:
            - Path=/config-
#            change the date for future and see the route will be 404
            - After=2021-01-20T17:42:47.789-07:00[America/Denver]
          uri: https://spring.io